import { type NextPage } from "next";
import Head from "next/head";
import Navbar from '../components/Navbar'
import Main from '../components/Main'
import Experience from '../components/Experience'
import Skills from '../components/Skills'
import Footer from '../components/Footer'


import { api } from "../utils/api";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Chris Lee</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-screen-xl m-auto">
      <Navbar/>
      <Main/>
      <Experience/>
      <Skills/>
      <Footer/>
      </div>


      

    </>
  );
};

export default Home;
